project:
  type: website

website:
  page-navigation: true
  title: "textalignment"
  site-url: https://bnosac.github.io/localllm/
  repo-url: https://github.com/bnosac/localllm
  repo-actions: [issue]
  page-footer: 
    left: "LocalLLM - &copy; BNOSAC"
  navbar:
    pinned: true
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Reference"
        file: reference/index.qmd
    right:
      - icon: github
        href: https://github.com/bnosac/localllm
        aria-label: GitHub repository    

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml

format:
  html:
    theme:
      - flatly

quartodoc:
  package: localllm
  style: pkgdown
  sections:
    - title: LocalLLM utilities
    - subtitle: Utilities
      desc: Download common local LLM Models
      contents:
        - localllm_download_model
    - subtitle: LocalLLM alongside DSPy
      desc: Use a LocalLLM model with DSPy
      contents:
        - name: dspy.LocalLLM

