name: docs 

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  deploy-docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - uses: astral-sh/setup-uv@v7
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          QUARTO_PYTHON: .venv/bin/python3
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build reference documentation
        run: |  
          uv sync --all-extras --group dev
          uv pip install .
          uv run quartodoc build --config doc/_quarto.yml          
      - name: Add venv to PATH
        run: echo "$(pwd)/.venv/bin" >> $GITHUB_PATH                
      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: doc
          render: true